AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    go-serverless-testing

    Sample SAM Template for go-serverless-testing

Globals:
    Function:
        Timeout: 29
        MemorySize: 256

Resources:
    PDFGeneratorFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: pdf-generator/cmd/
            Handler: main
            Runtime: go1.x
            Architectures:
                - x86_64
